#version: '3'
#
#services:
#  postgres:
#    image: 'postgres'
#    container_name: 'java-postgres'
#    ports:
#      - 5432:5432
#    environment:
#      - 'POSTGRES_USER=steshko'
#      - 'POSTGRES_HOST_AUTH_METHOD=trust'
#      - 'POSTGRES_DB=java'