spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/vote-docker-db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:postgresql://localhost:5432/vote-docker-db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: steshko
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
